@PurchaseGateway.Api_HostAddress = http://localhost:9999

POST {{PurchaseGateway.Api_HostAddress}}/payments
Content-Type: application/json
{
  "correlationId": "{{$guid}}",
  "amount": {{$randomInt}}.{{$randomInt}}
}


###


GET {{PurchaseGateway.Api_HostAddress}}/payments-summary?from=2021-07-10T12:34:56.000Z&to=2026-07-20T12:35:56.000Z
Content-Type: application/json
{}


###


GET {{PurchaseGateway.Api_HostAddress}}/purge-db
Content-Type: application/json
{}

