name: rinha-de-backend-purchase-gateway

x-services:
  purchase-gateway: &purchase-gateway
    image: pancine/rinha-de-backend-2025-purchase-gateway:latest
    environment:
      - ConnectionStrings__Redis=purchase-gateway-redis:6379
      - ConnectionStrings__Postgres=Host=purchase-gateway-db;Username=postgres;Password=pwd;Database=purchases
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - PURCHASE_WORKERS=6
    networks:
      - payment-processor
      - purchase-gateway
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "65MB"
    depends_on:
      - purchase-gateway-redis
      - purchase-gateway-db

services:
  purchase-gateway-load-balancer:
    image: nginx:latest
    container_name: purchase-gateway-load-balancer
    ports:
      - 9999:9999
    networks:
      - payment-processor
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "15MB"
    depends_on:
      - purchase-gateway-1
      - purchase-gateway-2

  purchase-gateway-1:
    <<: *purchase-gateway
    container_name: purchase-gateway-1

  purchase-gateway-2:
    <<: *purchase-gateway
    container_name: purchase-gateway-2

  purchase-gateway-redis:
    image: redis:8.0-alpine
    container_name: purchase-gateway-redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - purchase-gateway
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "10MB"

  purchase-gateway-db:
    image: postgres:17
    container_name: purchase-gateway-db
    restart: always
    environment:
      - POSTGRES_PASSWORD=pwd
      - POSTGRES_DB=purchases
    ports:
      - 5432:5432
    networks:
      - purchase-gateway
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "200MB"

networks:
  payment-processor:
    external: true

  purchase-gateway:
    name: purchase-gateway
    driver: bridge

volumes:
  healthcheck:
