name: rinha-de-backend

x-services:
  purchase-gateway: &purchase-gateway
    image: pancine/rinha-de-backend-2025-purchase-gateway:latest
    networks:
      - payment-processor
    volumes:
      - healthcheck:/app/healthcheck
    deploy:
      resources:
        limits:
          cpus: "0.60"
          memory: "164MB"
    depends_on:
      - health-check

services:
  load-balancer:
    image: nginx:latest
    container_name: load-balancer
    ports:
      - 9999:9999
    networks:
      - payment-processor
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "15MB"
    depends_on:
      - purchase-gateway-1
      - purchase-gateway-2

  purchase-gateway-1:
    <<: *purchase-gateway
    container_name: purchase-gateway-1
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080

  purchase-gateway-2:
    <<: *purchase-gateway
    container_name: purchase-gateway-2
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080

  health-check:
    image: pancine/rinha-de-backend-2025-hc:latest
    container_name: health-check
    environment:
      - DEFAULT_HC_URL=http://payment-processor-default:8080/payments/service-health
      - FALLBACK_HC_URL=http://payment-processor-fallback:8080/payments/service-health
    networks:
      - payment-processor
    volumes:
      - healthcheck:/app/healthcheck
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "6MB"

networks:
  payment-processor:
    external: true

volumes:
  healthcheck: